### ISSUE TITLE
[Context] Rename additionalTaxCountries to storeRegistrations

### ISSUE THREAD

**Issue by bojanz** [commerceguys/tax#14]
Internal feedback tells me this is more intuitive.

**Comment by neilcrookespm** [comment]
Agreed, although, following on from our [twitter conversation](https://twitter.com/neilcrookes/status/564763377700843521), consider the following scenario:

A french company, registered for VAT in France, is also registered for VAT in Corsica because their revenue from that zone exceeds a threshold, and the customer address is also in Corsica.

Should the customer be charged [Corsican VAT](https://github.com/commerceguys/tax/blob/master/resources/tax_type/fr_h_vat.json) rather than [French VAT](https://github.com/commerceguys/tax/blob/master/resources/tax_type/fr_vat.json)?

If the additionalTaxCountries / storeRegistrations parameter to Context::__construct() is an array of country codes, this won't be possible, because Corsica is in France, and an 'FR' country code would be passed in, so the customer would always get charged French VAT.

**Comment by bojanz** [comment]
Discussed this with David (our tax expert). Basically, Corsican VAT is still paid to France, so you don't register for Corsican VAT, just for French VAT. Same situation with Portuguese or Greek islands.

**Comment by neilcrookespm** [comment]
Thanks for your reply @bojanz, and please pass on my thanks to David.

But presumably a company, who's address is in Corsica, can register for Corsican VAT (otherwise Corsican VAT would never get applied to any transactions so there would be any point in it). So is it just companies who's main address is outside Corsica, that cannot register for VAT inside Corsica? The Corsican VAT Authority are missing out there aren't they!? ;)

**Comment by bojanz** [comment]
AFAIK, there is no Corsican VAT authority, just the French VAT authority. Companies registered in Corsica have the right to use France's special rates for Corsica. Also, a company from outside of France selling a digital product to Corsica would charge those same rates. In the end, France gets all the dough :)

**Comment by neilcrookespm** [comment]
Thanks for clarifying @bojanz.

**Comment by bojanz** [comment]
Done in 115d1f47bb8eebb24cd23fe1135e28fc1cbce9cb
