### ISSUE TITLE
VAT rate abbreviations

### ISSUE THREAD

**Issue by adamlc** [commerceguys/tax#24]
I was redesigning our invoices and I thought it might be nice to include the abbreviations for each country in the TaxType as some meta data. I was going to implement this myself but then figured it made much more sense in this library!

You can find a list of all the abbreviations on [Wikipedia](https://en.wikipedia.org/wiki/European_Union_value_added_tax#VAT_rates)

**Comment by bojanz** [comment]
That's the point of the GenericLabel property and enum: https://github.com/commerceguys/tax/blob/master/src/Enum/GenericLabel.php

Note that VAT is used for all european countries, because their abbreviations are just translations of VAT. I didn't want to include the translated versions because we'd need to start caring about locale, and some like Switzerland and Belgium even have multiple translations since they have multiple official languages.
So, my recommendation is to translate the generic label using your framework's string translation, providing the versions for the locales you use.

**Comment by adamlc** [comment]
Fair enough! I hadn't thought about that, thanks :smiley_cat:
