### ISSUE TITLE
Do not calculate customer's VAT on small business, making less than 10k euro

### ISSUE THREAD

**Issue by pavkatar** [commerceguys/tax#68]
There is new law in EU from 1st of January 2019, regarding the calculated VAT percentage for the EU purchases B2C. 

> 3. Should a taxable person deregister from the Union scheme as from 1 January 2019 if the total value of his supplies of telecommunications, broadcasting and electronically supplied services to non-taxable persons in other Member States in 2018 did not exceed EUR 10,000?
 
> The place of supply of telecommunications, broadcasting and electronically supplied services to non-taxable persons in other Member States is, in principle, in the Member State of the customer. However, to reduce the administrative burden for small businesses, a derogation to this principle has been introduced, entering into force on 1 January 2019. It provides that the place of supply of these services is in the Member State of the supplier where he is established or, in the absence of an establishment, has his permanent address or usually resides in only one Member State and the total value of these supplies does not exceed EUR 10,000 (exclusive of VAT) in the current and the preceding calendar year. The supplier can opt to apply the Member State of the customer-rule though and will in this case be bound by this decision for two calendar years. As soon as the threshold is exceeded, the place of supply is in the Member State of the customer (no option possible).
> 
> This means that taxable persons whose relevant supplies of services did not exceed the value of EUR 10,000 in 2018 can voluntarily deregister from the Union scheme in 2019. They are however not obliged to do so and can opt to apply the general place of supply rule (taxation in the Member State of the customer) and continue using the mini One Stop Shop, in particular if they expect that their turnover is going to exceed this threshold in 2019.

**Comment by pavkatar** [comment]
Hi guys, any news regarding this? What do you think?

**Comment by pjcarly** [comment]
Am I incorrect to understand, that it doesn't depend on whether the Customer is tax exempt? But the seller.

A seller selling less than 10K EUR can choose to deregister, and should not charge VAT to its customers. But at the same time, the seller cannot recover charged taxes.

**Comment by pavkatar** [comment]
If the company is selling for less than 10k EUR per year to foreigner customers, the company is not forced to register into MOSS. If the company is not registered into MOSS, it is not required for it to work with the customer's location VAT. 

So in a nutshell, If I am a customer from Germany (standard VAT: 19%), buying a good from Greece(standard VAT: 24%), the company have to sell me with 24%, not with 19%, which is in the case, when the company is registered in MOSS

**Comment by pjcarly** [comment]
I agree, under certain conditions:

- The customer doesn't have a VAT number (else it would be tax exempt under IC)
- The good that is being sold isn't a digital good, like an e-book, or music (else the seller would be required to charge German VAT)
- The good being sold isn't sold through a German POS, or being shipped from a German warehouse (else it would be German VAT again)
- The seller isn't above the yearly threshold for Germany, as defined [here](https://ec.europa.eu/taxation_customs/sites/taxation/files/resources/documents/taxation/vat/traders/vat_community/vat_in_ec_annexi.pdf) (else the seller would be required to charge German VAT)


But your question is regarding the choice for a seller to not charge VAT at all because the seller is a small business and chose to be VAT exempt.

How would you like to see that in this library? You could fix it with a custom Resolver.

**Comment by dmnc** [comment]
Closed as if the seller does not wish to charge VAT, they shouldn't register a VAT resolver.
