### ISSUE TITLE
Resolve rate change ambiguity

### ISSUE THREAD

**Issue by bojanz** [commerceguys/tax#8]
I've seen this for Ireland and Slovakia, in the linked PDF source.

For Ireland, until 01/07/2011 there were two non-rates: 4.8 and 13.5.
We'd call them "Super-Reduced" and "Reduced". 
From 01/07/2011 there are three rates: 4.8 / 9 / 13.5.
4.8 is still super-reduced, but Reduced is now 9, and 13.5 is Intermediate.

What is more correct:
1) Treating 13.5 as the intermediate rate historically, and specifying
that Reduced starts on 01/07/2011
2) Treating 13.5 -> 9 as the Reduced rate change, and introducing the 13.5 as
the Intermediate since 01/07/2011?

The ie_vat definition currently follows #1, but this needs confirming.

**Comment by dwkitchen** [comment]
There is a limited standard on what to call rates, anything less that 5% is a "Super-Reduced" rate.

As far as the Europa is concerned anything between 5% and the standard rate is a reduced rate. Reduced and Intermediate was just a convention I used in the D7 VAT module because that's what France uses.

Ireland calls the 13.5 "Reduced" and 9% "Second Reduced" http://www.revenue.ie/en/tax/vat/rates/current-historic-rates-vat.html

It is a case of trying to get the right naming for each country, which isn't shown in the Europa documents.

**Comment by dwkitchen** [comment]
We can close this.
